"""Adding the user location

Revision ID: 4604db61b3fe
Revises: aba122a67747
Create Date: 2019-02-10 14:32:25.185391

"""
from alembic import op
import sqlalchemy as sa
import geoalchemy2

# revision identifiers, used by Alembic.
revision = '4604db61b3fe'
down_revision = 'aba122a67747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('geog', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326), nullable=True))
    op.create_index(op.f('ix_user_geog'), 'user', ['geog'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_geog'), table_name='user')
    op.drop_column('user', 'geog')
    # ### end Alembic commands ###
